// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",seed: 'ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts',
  },
  datasource: {
    // Session pooler (puerto 5432) o transaction pooler (6543) — usamos DATABASE_URL
    // porque el puerto 5432 puede estar bloqueado en redes locales.
    url: process.env["DATABASE_URL"],
  },
});
