// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // La CLI de Prisma 7 usará esta URL para correr las migraciones.
    // Para Supabase, las migraciones DEBEN usar la conexión directa.
    url: process.env["DIRECT_URL"],
  },
});
